More changes

diff --git a/dockerfiles/runit/pve-daemon/run b/dockerfiles/runit/pve-daemon/run
--- a/dockerfiles/runit/pve-daemon/run
+++ b/dockerfiles/runit/pve-daemon/run
@@ -5,5 +5,22 @@ if [[ ! -e /run/pve-cluster.pid ]]; then
   exit 1
 fi
 
+if ! mountpoint /run; then
+  echo "WARNING: The '/run' should be 'tmpfs' mountpoint. PBS might not work correctly."
+fi
+
+for mp in /etc/pve /var/lib/vz; do
+  if ! mountpoint "$mp"; then
+    echo "ERROR: The '$mp' should be volume."
+    exit 1
+  fi
+done
+
+if [[ ! -e /etc/pve/.first ]]; then
+  echo "DAEMON: Initial copy!"
+  cp -av ../../pve/. /etc/pve
+  touch /etc/pve/.first
+fi
+
 # /run/pvedaemon.pid
 exec /usr/bin/pvedaemon start --debug
